### ISSUE TITLE
Conditions screen: 'Next' button is enabled though user didn't give any condition

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#1]
Conditions screen: 'Next' button is enabled though user didn't give any condition

Steps to replicate:
1. Go to staging.pawsquad.co.uk and login
2. Click on talk to VET now in Home page
3. Give the Pet details and click on Next
4. Now, in conditions screen, just click on 'Next' and observe

Observed: We are taken to next page without giving any condition

Expected: Next button should be enabled, only after giving at least one condition

![next button in conditions screen](https://cloud.githubusercontent.com/assets/13519999/8940371/249ef936-3587-11e5-8f2e-a9aafc10dc4a.png)

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#212
