### ISSUE TITLE
Home Page: 'Sign Up' button still appears even though user is already login

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#10]
Home Page: 'Sign Up' button still appears even though user is already login

Steps to replicate:
1. Go to staging.pawsquad.co.uk and login to site and observe

Observed: 'Sign Up' button still appears even though user is already login

Expected: 'Sign Up' button should not appear after user login to site

![sign up after login](https://cloud.githubusercontent.com/assets/13519999/8943324/f18ec150-3597-11e5-8082-3c05979ca1a0.jpg)

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#203
