### ISSUE TITLE
Home Page: We see wrong title (Help) for 'Sign Up' button

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#11]
Home Page: We see wrong title for 'Sign Up' button

Steps to replicate:
1. Go to staging.pawsquad.co.uk and mouse hover on 'Sign Up'  and observe

Observed: We see wrong title (Help) for 'Sign Up' button

Expected: Button title should be Sigh Up

![wrong title](https://cloud.githubusercontent.com/assets/13519999/8943415/880feb40-3598-11e5-9f3a-9dae7324e435.jpg)

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#202
