### ISSUE TITLE
User Dashboard Home: "Talk to a VET now" text is not aligned to centre

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#12]
User Dashboard Home: "Talk to a VET now" text is not aligned to centre

Steps to replicate:
1. Go to staging.pawsquad.co.uk and login to site
2. Go to User dashboard home and observe

Observed: "Talk to a VET now" text is not aligned to centre

Expected: "Talk to a VET now" text should be aligned to centre

![talk to a vet now](https://cloud.githubusercontent.com/assets/13519999/8943664/819bf9b0-3599-11e5-85fb-32eec1251cd0.jpg)

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#200
