### ISSUE TITLE
User Dashboard Home: We see unnecessary scroll bar

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#13]
User Dashboard Home: We see unnecessary scroll bar

Steps to replicate:
1. Go to staging.pawsquad.co.uk and login to site
2. Go to User dashboard home and observe the scroll bar

Observed: We see unnecessary scroll bar

Expected: Scroll bar should not appear, we could reduce the extra space as shown in screenshot

![unnecessary scroll bar](https://cloud.githubusercontent.com/assets/13519999/8943797/343646d4-359a-11e5-853a-47177461aa7f.jpg)

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#199

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#201
