### ISSUE TITLE
[Suggestion] User Dashboard Home: We could highlight the icon in Dashboard with respect to the user presence

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#14]
[Suggestion] User Dashboard Home: We could highlight the icon in Dashboard with respect to the user 
presence

Steps to reach:
Steps to replicate:
1. Go to staging.pawsquad.co.uk and login to site
2. Go to User dashboard home and observe

Observed: We are not highlighting the respective icon. 

Expected: it would be good to highlight the icon with respect to the user presence.
Ex: When user is in dashboard home, then Home icon should be highlighted as shown in screenshot

![suggestion in dashboard](https://cloud.githubusercontent.com/assets/13519999/8943958/4be20fb0-359b-11e5-959c-527f88f7e8d6.jpg)

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#198
