### ISSUE TITLE
Forgot Password: Nothing happens when we click on request button with unregisted email

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#2]
Forgot Password: Nothing happens when we click on request button with unregisted email

Steps to replicate:
1. Go to staging.pawsquad.co.uk and click on login
2. Click on forgot password link
3. Give any unregistered email ID and click on 'Request' button

Observed: Nothing happens, we don't see any error message.

Expected: System should give an error message to user that email was not registered with Pawsquad.

![forgot password](https://cloud.githubusercontent.com/assets/13519999/8940852/bd213398-3589-11e5-8cc9-ca5a8e200d21.png)

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#211
