### ISSUE TITLE
Home Page: 'See more' link is not working at 'More about Pawsquad' section

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#3]
Home Page: 'See more' link is not working at 'More about Pawsquad' section

Steps to replicate:
1. Go to staging.pawsquad.co.uk
2. Scroll the page down to 'More about Pawsquad' section
3. Click on 'See more' link and observe

Observed: 'See more' link is not working at 'More about Pawsquad' section

Expected: 'See more' link should work and takes user to the page with more info!

![see more](https://cloud.githubusercontent.com/assets/13519999/8941176/c0830712-358b-11e5-9e42-2a5bce5052f9.jpg)

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#210
