### ISSUE TITLE
Home Page: We see sample text at 'More about Pawsquad' section

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#4]
Home Page: We see sample text at 'More about Pawsquad' section

Steps to replicate:
1. Go to staging.pawsquad.co.uk
2. Scroll the page down to 'More about Pawsquad' section
3. Click on any of the 2nd, 3rd or 4th tab and observe

Observed: We see sample text at 'More about Pawsquad' section

Expected: text has to be updated according to the tab
![sample text](https://cloud.githubusercontent.com/assets/13519999/8941597/15fcfbce-358e-11e5-8450-374bc80ac105.jpg)

Also at 'Meet a few of our VETS' section, we see only same data for all VET details, http://ipic.su/img/img7/fs/kiss_100kb.1437833083.jpg

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#209
