### ISSUE TITLE
Home Page: Navigation icon disappears near 'Meet a few of our VETS' section in Home page, but works when we click at that position.

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#5]
Home Page: Navigation icon disappears near 'Meet a few of our VETS' section in Home page, but works when we click at that position.

Steps to replicate:
1. Go to staging.pawsquad.co.uk
2. Scroll the page down to 'Meet a few of our VETS' section
3. Click on the Next button on right hand side, http://f5.s.qip.ru/cMfvVDKl.jpg
4. Go to last screen and observe

Observed: Navigation icon disappears near 'Meet a few of our VETS' section in Home page, but works when we click at that position.

Expected: Navigation icon should display in the last and first screen as well

![next icon](https://cloud.githubusercontent.com/assets/13519999/8942155/9a0427fa-3591-11e5-93c7-6ab1d94ff73b.jpg)

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#208
