### ISSUE TITLE
Home Page: We see difference in site logo at header and footer section, also tag is not present at header

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#6]
We see difference in site logo at header and footer section, also tag is not present at header

Steps to replicate:
1. Go to staging.pawsquad.co.uk
2. Scroll the page down to bottom and observe the logo

Observed: We see difference in site logo at header and footer section. Also we see the tag 'Video Vets on Demand' at footer, but we don't see it in header logo.

Expected: Logo should be same everywhere.

![logo](https://cloud.githubusercontent.com/assets/13519999/8942293/340f4faa-3592-11e5-8fa5-d90e09913c3b.jpg)

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#207
