### ISSUE TITLE
Pet Details Page: Tick mark is missing in Pet details page, when we choose 'Yes' radio button for "Neutered status", but we see it for 'No' radio button

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#7]
Tick mark is missing in Pet details page, when we choose 'Yes' radio button for "Neutered status", but we see it for 'No' radio button

Steps to replicate:
1. Go to staging.pawsquad.co.uk and login
2. Click on 'Talk to a Vet now' link and go to Pet details page
3. Select No radio button for "Neutered status" and observe the green tick mark
4. Now, select 'Yes' and observe

Observed: Tick mark is missing in Pet details page, when we choose 'Yes' radio button for "Neutered status"

Expected: Tick mark should be displayed, when user select yes option

![green tick at yes](https://cloud.githubusercontent.com/assets/13519999/8942429/f718cbca-3592-11e5-9270-a3c15c3854ec.jpg)

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#206
