### ISSUE TITLE
Reset Password: We see alignment missing at password confirmation field 

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#8]
We see alignment missing at password confirmation field

Steps to replicate:
1. Go to staging.pawsquad.co.uk and click on login link
2. Click on "Forgot your login details?" link 
3. Provide any registered email ID and click on Request
4. Go to email and click on 'Reset Password' link and observe

Observed: We see alignment missing at password confirmation field

Expected: Password confirmation should be aligned properly

![confirm password](https://cloud.githubusercontent.com/assets/13519999/8942759/da1a62a2-3594-11e5-8a30-2f40bf0d28ec.png)

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#205
