### ISSUE TITLE
Expert Dashboard: After accepting the call, we see both Shift & Availability as OFF with blank page

### ISSUE THREAD

**Issue by Harish090** [pawztech/frontend-test#9]
Expert Dashboard: After accepting the call, we see both Shift & Availability as OFF with blank page

Steps to replicate:
1. Go to Expert account and wait for any call to accept
2. Receive the call and observe both Shift & Availability status

Observed: After accepting the call, we see both Shift & Availability as OFF with blank page

Expected: Both Shift & Availability status should be Yes and video should be loaded

![shift availability](https://cloud.githubusercontent.com/assets/13519999/8943113/b30ef09a-3596-11e5-90e9-ed715517e36a.jpg)

**Comment by martyzz1** [comment]
This issue was moved to pawztech/api#204
